"""
batch_add_missing.py — Add all tickers that are listed on TWSE/OTC but missing from the DB.

Reads missing_tickers.json (generated by compare_listings.py or the discovery step),
then calls add_ticker.generate_report() for each one with a delay to avoid rate-limiting.

Usage:
  python scripts/batch_add_missing.py                  # Add all missing
  python scripts/batch_add_missing.py --dry-run        # Preview only
  python scripts/batch_add_missing.py --skip-dr        # Skip 6-digit DR tickers
"""

import json
import os
import sys
import time
import argparse

if sys.platform == "win32":
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from add_ticker import generate_report, sanitize_folder_name
from utils import find_ticker_files, REPORTS_DIR

MISSING_FILE = os.path.join(os.path.dirname(os.path.dirname(__file__)), "missing_tickers.json")


def main():
    parser = argparse.ArgumentParser(description="Batch-add missing tickers to the DB")
    parser.add_argument("--dry-run", action="store_true", help="Preview only, do not write files")
    parser.add_argument("--skip-dr", action="store_true", help="Skip 6-digit DR tickers")
    parser.add_argument("--delay", type=float, default=1.5, help="Seconds between each ticker (default: 1.5)")
    args = parser.parse_args()

    if not os.path.exists(MISSING_FILE):
        print(f"ERROR: {MISSING_FILE} not found. Run the discovery step first.")
        sys.exit(1)

    with open(MISSING_FILE, encoding="utf-8") as f:
        missing = json.load(f)

    # Sort numerically
    items = sorted(missing.items(), key=lambda x: int(x[0]) if x[0].isdigit() else 99999)

    if args.skip_dr:
        items = [(t, n) for t, n in items if len(t) <= 4]

    total = len(items)
    print(f"{'[DRY RUN] ' if args.dry_run else ''}Found {total} tickers to add.\n")

    success, failed, skipped = 0, 0, 0

    for i, (ticker, name) in enumerate(items, 1):
        # Double-check it's not already in DB (race condition guard)
        existing = find_ticker_files(ticker)
        if existing:
            print(f"[{i}/{total}] SKIP {ticker} {name} — already exists")
            skipped += 1
            continue

        if args.dry_run:
            print(f"[{i}/{total}] WOULD ADD {ticker} {name}")
            success += 1
            continue

        print(f"[{i}/{total}] Adding {ticker} {name} ...", end=" ", flush=True)
        try:
            content, detected_sector = generate_report(ticker, name)
            folder_name = sanitize_folder_name(detected_sector)
            output_dir = os.path.join(REPORTS_DIR, folder_name)
            os.makedirs(output_dir, exist_ok=True)
            safe_name = sanitize_folder_name(name)  # removes * and other illegal chars
            filepath = os.path.join(output_dir, f"{ticker}_{safe_name}.md")
            with open(filepath, "w", encoding="utf-8") as f:
                f.write(content)
            print(f"OK -> {folder_name}/{ticker}_{name}.md")
            success += 1
        except Exception as e:
            print(f"ERROR: {e}")
            failed += 1

        # Rate-limit guard
        if i < total:
            time.sleep(args.delay)

    print(f"\n{'[DRY RUN] ' if args.dry_run else ''}Done. Added: {success} | Skipped: {skipped} | Failed: {failed}")


if __name__ == "__main__":
    main()
